version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - OPENROUTER_API_KEY=your_openrouter_api_key_here